// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGuQy9zJgVeKGN7u9Df4vvwT2cGlRq_l4',
    appId: '1:873614776209:android:5fd2cd0a4139883913ec30',
    messagingSenderId: '873614776209',
    projectId: 'bank-app-92995',
    storageBucket: 'bank-app-92995.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkRGP0DYwxUuUmsK3Wj9MeaTPozHi3NAQ',
    appId: '1:873614776209:ios:679409052294b04713ec30',
    messagingSenderId: '873614776209',
    projectId: 'bank-app-92995',
    storageBucket: 'bank-app-92995.appspot.com',
    androidClientId: '873614776209-4slghap1fe4o9bdlidfet7ugfrg93r3g.apps.googleusercontent.com',
    iosClientId: '873614776209-31um5u739di406vsps4e14j7guotrtif.apps.googleusercontent.com',
    iosBundleId: 'no.ntnu.bankApp',
  );
}
